version: "3"
networks:
  localnetwork:
    driver: bridge

services:
  fastify-server:
    build:
      context: .
      dockerfile: ./fastify-server/Dockerfile
    networks:
      - localnetwork
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - "./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml"
    networks:
      - localnetwork
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter:v1.8.0
    networks:
      - localnetwork
    ports:
      - 9100:9100
