global:
  scrape_interval: "10s"
scrape_configs:
  - job_name: fastify-server
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
    static_configs:
      - targets:
          - 172.21.0.100:3002
          - 172.21.0.104:8000
